### ISSUE TITLE
Move the package to SublimeText org

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/InsertNums#29]
Hi @jbrooksuk,

I'd like to move this package to the SublimeText org with your approval. The last notable changes to it were made 10 years ago and it's basically been unmaintained since then (but it also still works just fine and I use it regurlarly). However, in order to prevent it from potentially being lost in the aether of unmaintained stuff and in case you yourself lose interest in it, I'd like to move it to the org where we have serveral admins to handle maintainership changes et al.

The trigger for this was that I noticed the package's homepage pointing to https://james-brooks.uk/, which is defunct, and I as a contributor (the highest non-owner permission level for account-owned repositories) cannot change this level of setting despite being a co-author of the package.

Please let me know if you're in support of this. You could either transfer the repo to me or I add you to the org (if you're not already a member) and you can transfer it there yourself, whatever you prefer. I'll handle the rest, i.e. updating the Package Control entry.

**Comment by jbrooksuk** [comment]
@FichteFoll yeah, I'm happy to do that. Let's update the package's homepage to the GitHub repo.

I'll transfer this to the SublimeText org now.

**Comment by jbrooksuk** [comment]
This is now done 👍🏻

**Comment by FichteFoll** [comment]
Changes have also been made on the PC channel repo.
